export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Rancho",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Anita",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Ankita",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Happu",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Saxena",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Guiyan ke doctor",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Prem",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Anguri",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Mallika",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Katori",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Dieing to win, and Wining to die or two completely different things.",
    photo: "assets/post/1.jpeg",
    date: "5 decade ago..",
    userId: 1,
    like: 20000,
    Comment: 145555,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 decade ago..",
    userId: 2,
    like: 200,
    Comment: 1,
  },
  {
    id: 3,
    desc: "I didn't said this",
    photo: "assets/post/3.jpeg",
    date: "35 decade ago..",
    userId: 3,
    like: 153,
    Comment: 78,
  },
  {
    id: 4,
    desc: "I am the Flash, not we are the Flash. You damb idiot...",
    photo: "assets/post/4.jpeg",
    date: "yesterday...",
    userId: 4,
    like: 16,
    Comment: 763,
  },
  {
    id: 5,
    desc: "I just need a year's sleep and a new body.",
    photo: "assets/post/5.jpeg",
    date: "15 days ago..",
    userId: 5,
    like: 46,
    Comment: 8,
  },
  {
    id: 6,
    desc: "It is so much morning, that it's actually still yesterday.",
    photo: "assets/post/6.jpeg",
    date: "3 hours ago..",
    userId: 6,
    like: 316,
    Comment: 185,
  },
  {
    id: 7,
    desc: "If you don't have own story, you become part of someone else's.",
    photo: "assets/post/7.jpeg",
    date: "19 hours ago..",
    userId: 7,
    like: 93,
    Comment: 76,
  },
  {
    id: 8,
    desc: "If you have a God, then you probably also have a Devil. And if God created everything, then he also made Hell.",
    photo: "assets/post/8.jpeg",
    date: "25 minutes ago..",
    userId: 8,
    like: 468,
    Comment: 374,
  },
  {
    id: 9,
    desc: "I have no fear of death. It always sounded peaceful to me.",
    photo: "assets/post/9.jpeg",
    date: "4 days ago..",
    userId: 9,
    like: 4761,
    Comment: 1655,
  },
  {
    id: 10,
    desc: "I don't care.",
    photo: "assets/post/10.jpeg",
    date: "5 days ago..",
    userId: 10,
    like: 496,
    Comment: 753,
  },
];
